#!/usr/bin/env php
<?php
if(in_array('--help', $_SERVER['argv'])){
	// Show help
	echo <<<EOD
Usage: ./build [OPTIONS] [OUTPUT_DIRECTORY]

Builds the system into a Phar

  -c- Skip Composer installation
  -c+ Update Composer packages
  -p  Prepare packages
  -t  Run tests
  -r  Run the blog
  -v  Output detailed information
  --all  Build system, prepare packages, run tests and run blog
EOD;
	echo PHP_EOL;

	return;
}

ini_set('memory_limit','16M');

$scriptPath	= array_shift($_SERVER['argv']);

$dir	= 'blight';
$name	= 'Blight.phar';


$pathSource	= __DIR__.'/'.$dir;
$pathBuild	= end($_SERVER['argv']);
if(!$pathBuild || ($pathBuild[0] == '-' && strlen($pathBuild) <= 3) || $pathBuild === '--all'){
	// No path given
	$pathBuild	= __DIR__;
}

function consoleOutput($message, $detailed = true){
	global $verbose;
	if($detailed && !$verbose){
		return;
	}

	echo $message.PHP_EOL;
}

function quotedConsoleOutput($message, $detailed = true){
	$message	= trim($message);
	if(!$message){
		return;
	}

	return consoleOutput('> '.str_replace(PHP_EOL, PHP_EOL.'> ', $message), $detailed);
}

function consoleLinebreak($detailed = true){
	return consoleOutput('', $detailed);
}


function hasFlag($flag, $allowAll = true){
	$result	= in_array('-'.$flag, $_SERVER['argv']);
	if(!$result && $allowAll){
		$result	= hasFlag('-all', false);
	}

	return $result;
}

$verbose	= hasFlag('v', false);

try {
// Compose
	if(!hasFlag('c-', false)){
		consoleOutput('Updating Composer');

		$output	= shell_exec('composer '.(hasFlag('c+', false) ? 'update' : 'install'));

		consoleOutput('Updated Composer', false);
		quotedConsoleOutput($output);
	}

// Build
	consoleOutput('Building system');

	if(!is_dir($pathBuild)){
		mkdir($pathBuild);
	}

	$phar = new Phar($pathBuild.'/'.$name, 0, $name);
	$phar->buildFromDirectory($pathSource);

	// Update Composer to use Phar
	$path	= 'vendor/composer/autoload_classmap.php';
	if(file_exists(__DIR__.'/'.$dir.'/'.$path)){
		$content	= file_get_contents(__DIR__.'/'.$dir.'/'.$path);
		$content	= str_replace('/'.$dir.'/', '/'.$name.'/', $content);
		$phar->addFromString($path, $content);
	}

	$phar->setStub(file_get_contents($pathSource.'/phar-stub.php'));
	unset($phar);
	consoleOutput('Built system', false);

	consoleLinebreak();


// Package packages
	if(hasFlag('p')){
		consoleOutput('Preparing packages');

		ob_start();
		require('prepare_packages.php');
		consoleOutput('Prepared packages', false);

		quotedConsoleOutput(ob_get_clean());

		consoleLinebreak();
	}


// Run tests
	if(hasFlag('t')){
		consoleOutput('Running tests');

		$output	= shell_exec('phpunit -c tests/Blight/config.xml -v').PHP_EOL;
		$replaces	= array(
			'/PHPUnit .*? by Sebastian Bergmann.(?:\n)?/i'	=> '',
			'#Configuration read from (?:'.preg_quote(__DIR__, '#').'/)?(.*?\.xml)#i'	=> 'Config: $1',
			'/\R+/'	=> "\n"
		);
		foreach($replaces as $find => $replace){
			$output	= preg_replace($find, $replace, $output);
		}

		consoleOutput('Ran tests', false);
		quotedConsoleOutput($output);

		consoleLinebreak();
	}


// Run
	if(hasFlag('r')){
		require($pathBuild.'/Blight.phar');

		consoleLinebreak();
	}

} catch(\Exception $e){
	exit('Exception: '.$e->getMessage().' ('.$e->getFile().'#'.$e->getLine().')');
}
